worker_processes 5;
daemon off;
worker_rlimit_nofile 8192;

events {
  worker_connections 4096;
}

http {
    client_max_body_size 100M;
    client_body_buffer_size 100M;

    include /etc/nginx/mime.types;
    include /etc/nginx/fastcgi_params;

    index index.html index.htm index.php;
    default_type application/octet-stream;
    
    access_log /dev/stdout;
    error_log /dev/stdout;
    
    sendfile on;
    tcp_nopush on;
    server_names_hash_bucket_size 128;

    server {
        listen 80;
        listen [::]:80;
        server_name localhost;
        root /app;

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";

        index index.php;
        charset utf-8;

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }

        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            include /etc/nginx/fastcgi_params;
            fastcgi_read_timeout 300;
            fastcgi_connect_timeout 300;
            fastcgi_send_timeout 300;
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
    }
}
