[phases.install]
cmds = []

[start]
cmd = "sed -i 's|location ~ \\.php$|location / {\\n        try_files $uri $uri/ $uri.html =404;\\n    }\\n\\n    location ~ \\.php$|' /nginx.conf && php-fpm -D && nginx -g 'daemon off;'"
